name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.22.2"
          cache: npm
      - run: npm ci && npm run build
        env:
          VITE_ADMIN: ${{ vars.VITE_ADMIN }}
          VITE_API_BOT_NAME: ${{ vars.VITE_API_BOT_NAME }}
          VITE_WINDOWS: ${{ vars.VITE_WINDOWS }}
          VITE_ANIME: ${{ vars.VITE_ANIME }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_A_QUIZ_FRONTEND }}
          channelId: live
          projectId: a-quiz-frontend